version: '{build}'
image: Visual Studio 2017
cache:
  - client/insight/node_modules
environment:
  nodejs_version: "Current"

build_script:
- ps: |
    $tag = $(hg id -t -r '.^')
    function ver ($x) { c:\python36\python.exe build/version.py $x }
    if ($tag.StartsWith("mwi")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver mwi) `
            server/lib/BlackMaple.MachineWatchInterface
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } elseif ($tag.StartsWith("framework")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver framework) `
            server/lib/BlackMaple.MachineFramework
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } elseif ($tag.StartsWith("mazak")) {
        dotnet publish `
            -c Release -f net461 `
            /p:VersionPrefix=$(ver mazak) `
            --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
            server/machines/mazak/mazak.csproj

        yarn install --cwd client/insight
        yarn run --cwd client/insight build

        ./build/insight-installer-build.ps1 mazak $(ver mazak)
    } else {
        #dotnet build `
        #    /p:VersionPrefix=$(ver mwi) `
        #    --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
        #    server/lib/BlackMaple.MachineWatchInterface
        #dotnet build `
        #    /p:VersionPrefix=$(ver framework) `
        #    --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
        #    server/lib/BlackMaple.MachineFramework
        #dotnet build `
        #    /p:VersionPrefix=$(ver mazak) `
        #    --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
        #    server/machines/mazak/mazak.csproj

        node --version
        yarn install --cwd client/insight
        yarn run build --cwd client/insight
    }

test_script:
- ps: dotnet test server/test
- ps: yarn test --cwd client/insight

artifacts:
  - path: '**/*.nupkg'
    name: NugetPackages

  - path: '**/build-output/*.msi'
    name: Installers

deploy:
- provider: NuGet
  on:
    branch: default
    BMS_RELEASE_TO_NUGET: true
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: kj0pW91vWRjFl99SLY/sageGAghMFfmqFpNdJd7y+Q73eoImzcsnPCZYlwYxKIhs
