version: '{build}'
image: Visual Studio 2017
cache:
  - client/insight/node_modules
install:
- ps: Install-Product node 9
environment:
  bitbucket_auth:
    secure: rWSLJHgb9I+I5jdorS8K2T415gRW5nJ2Z23pM3DmhqQ=

build_script:
- ps: |
    function ver ($x) { c:\python36\python.exe build/version.py $x }
    $tag = $(hg id -t -r '.^')
    if ($tag.StartsWith("mwi")) {
        $mwisuffix = ""
        Set-AppveyorBuildVariable "BMS_RELEASE_MWI_TO_NUGET" "true"
    } else {
        $mwisuffix = "--version-suffix=pre." + $Env:APPVEYOR_BUILD_NUMBER
    }
    dotnet pack `
        --include-symbols `
        -c Release `
        /p:VersionPrefix=$(ver mwi) `
        $mwisuffix `
        server/lib/BlackMaple.MachineWatchInterface

- ps: |
    yarn --cwd client/insight install
    yarn --cwd client/insight run build
    dotnet pack `
        --include-symbols `
        -c Release `
        --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
        server/lib/BlackMaple.MachineFramework

- ps: |
    function ver ($x) { c:\python36\python.exe build/version.py $x }
    dotnet pack `
        --include-symbols `
        -c Release `
        /p:VersionPrefix=$(ver mazak) `
        --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
        server/machines/mazak/mazak.csproj
    dotnet publish `
        -c Release `
        -f net461 `
        /p:VersionPrefix=$(ver mazak) `
        --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
        server/machines/mazak/mazak.csproj

    ./build/insight-installer-build.ps1 mazak

    $tag = $(hg id -t -r '.^')
    if ($tag.StartsWith("mazak")) {
        cd installers
        Remove-Item alias:curl
        curl -X POST `
            --silent --show-error `
            --user $ENV:bitbucket_auth `
            "https://api.bitbucket.org/2.0/repositories/blackmaple/machinewatch/downloads" `
            --form `
            files=@"FMS Insight Mazak Install.msi"
    }

test_script:
- ps: dotnet test server/test
- ps: ($env:CI = $true) -and (yarn --cwd client/insight test 2>&1 | Write-Host)

artifacts:
  - path: '**/*.nupkg'
    name: NugetPackages

  - path: 'installers/*.msi'
    name: Installers

deploy:
- provider: NuGet
  on:
    branch: default
    BMS_RELEASE_MWI_TO_NUGET: true
  skip_symbols: false
  artifact: /.*BlackMaple\.MachineWatchInterface.*\.nupkg/
  api_key:
    secure: kj0pW91vWRjFl99SLY/sageGAghMFfmqFpNdJd7y+Q73eoImzcsnPCZYlwYxKIhs