version: '{build}'
image: Visual Studio 2017

build_script:
- ps: |
    $tag = $(hg id -t -r '.^')
    function ver ($x) { c:\python36\python.exe version.py $x }
    if ($tag.StartsWith("mwi")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver mwi) `
            server/lib/BlackMaple.MachineWatchInterface
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } elseif ($tag.StartsWith("framework")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver framework) `
            server/lib/BlackMaple.MachineFramework
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } elseif ($tag.StartsWith("service")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver service) `
            server/src/service
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } else {
        dotnet build `
            /p:VersionPrefix=$(ver mwi) `
            --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
            server/lib/BlackMaple.MachineWatchInterface
        dotnet build `
            /p:VersionPrefix=$(ver framework) `
            --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
            server/lib/BlackMaple.MachineFramework
        dotnet build `
            /p:VersionPrefix=$(ver service) `
            --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
            server/src/service
    }

test_script:
- ps: dotnet test server/test

artifacts:
- path: '**/*.nupkg'

deploy:
- provider: NuGet
  on:
    branch: default
    BMS_RELEASE_TO_NUGET: true
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: kj0pW91vWRjFl99SLY/sageGAghMFfmqFpNdJd7y+Q73eoImzcsnPCZYlwYxKIhs
