version: "{build}"
image: Visual Studio 2017
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - '%USERPROFILE%\.nuget\packages'
install:
  - ps: Install-Product node 10
environment:
  bitbucket_auth:
    secure: rWSLJHgb9I+I5jdorS8K2T415gRW5nJ2Z23pM3DmhqQ=
init: tzutil /s "Pacific Standard Time"

build_script:
  - ps: |
      function ver ($x) { c:\python36\python.exe build/version.py $x }
      $tag = $(hg id -t -r '.^')
      if ($tag.StartsWith("insightapi")) {
          $vsuffix = ""
          Set-AppveyorBuildVariable "BMS_RELEASE_INSIGHT_API_TO_NUGET" "true"
      } else {
          $vsuffix = "--version-suffix=pre." + $Env:APPVEYOR_BUILD_NUMBER
      }
      dotnet pack `
          --include-symbols `
          -c Release `
          /p:VersionPrefix=$(ver insightapi) `
          $vsuffix `
          client/csharp-api

  - ps: |
      function ver ($x) { c:\python36\python.exe build/version.py $x }
      $tag = $(hg id -t -r '.^')
      if ($tag.StartsWith("mwi")) {
          $mwisuffix = ""
          Set-AppveyorBuildVariable "BMS_RELEASE_MWI_TO_NUGET" "true"
      } else {
          $mwisuffix = "--version-suffix=pre." + $Env:APPVEYOR_BUILD_NUMBER
      }
      dotnet pack `
          --include-symbols `
          -c Release `
          /p:VersionPrefix=$(ver mwi) `
          $mwisuffix `
          server/lib/BlackMaple.MachineWatchInterface

  - ps: |
      yarn --cwd client/insight install --frozen-lockfile
      yarn --cwd client/insight run build
      dotnet pack `
          --include-symbols `
          -c Release `
          --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
          server/lib/BlackMaple.MachineFramework

  - ps: |
      function ver ($x) { c:\python36\python.exe build/version.py $x }
      $tag = $(hg id -t -r '.^')
      dotnet pack `
          --include-symbols `
          -c Release `
          /p:VersionPrefix=$(ver mazak) `
          --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
          server/machines/mazak/mazak.csproj
      if ($tag.StartsWith("mazak")) {
        dotnet publish `
            -c Release `
            -f net461 `
            /p:VersionPrefix=$(ver mazak) `
            --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
            server/machines/mazak/mazak.csproj

        ./build/insight-installer-build.ps1 mazak
      }

  - ps: |
      function ver ($x) { c:\python36\python.exe build/version.py $x }
      $tag = $(hg id -t -r '.^')
      dotnet pack `
          --include-symbols `
          -c Release `
          /p:VersionPrefix=$(ver makino) `
          --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
          server/machines/makino/makino.csproj
      if ($tag.StartsWith("makino")) {
        dotnet publish `
            -c Release `
            -f net461 `
            /p:VersionPrefix=$(ver makino) `
            --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
            server/machines/makino/makino.csproj

        ./build/insight-installer-build.ps1 makino
      }

  - ps: |
      function ver ($x) { c:\python36\python.exe build/version.py $x }
      $tag = $(hg id -t -r '.^')
      dotnet pack `
          --include-symbols `
          -c Release `
          /p:VersionPrefix=$(ver cincron) `
          --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
          server/machines/cincron/cincron.csproj
      if ($tag.StartsWith("cincron")) {
        dotnet publish `
            -c Release `
            -f net461 `
            /p:VersionPrefix=$(ver cincron) `
            --version-suffix build.$Env:APPVEYOR_BUILD_NUMBER `
            server/machines/cincron/cincron.csproj

        ./build/insight-installer-build.ps1 cincron
      }

  - ps: |
      yarn --cwd client/insight run build-demo
      yarn --cwd website install --frozen-lockfile
      yarn --cwd website run build
      Copy-Item "client\insight\demo" -Destination "website\build\fms-insight\demo" -Recurse -Force
      7z a website.zip .\website\build\fms-insight\*

  - ps: |
      $tag = $(hg id -t -r '.^')
      if ($tag.StartsWith("backup-viewer")) {
        yarn --cwd client/backup-viewer install --frozen-lockfile
        yarn --cwd client/backup-viewer dist
        New-Item -ItemType Directory -Force -Path installers
        Copy-Item "client\backup-viewer\package\*.exe" -Destination "installers\FMS Insight Backup Viewer Install.exe" -Force
        Set-AppveyorBuildVariable "BMS_INSTALLER_backup_RELEASE" "true"
      }

test_script:
  - cmd: dotnet test server/test

artifacts:
  - path: "**/*.nupkg"
    name: NugetPackages

  - path: "installers/*.msi"
    name: Installers

  - path: "installers/*.json"
    name: InstallerVersions

  - path: "website.zip"
    name: Website
    type: zip

  - path: "installers/*.exe"
    name: Installers NSIS

deploy:
  - provider: NuGet
    on:
      branch: default
      BMS_RELEASE_MWI_TO_NUGET: true
    skip_symbols: false
    artifact: /.*BlackMaple\.MachineWatchInterface.*\.nupkg/
    api_key:
      secure: G2TzGogQH+sScPOuDvM6Cp3lEo8ibadnPBsSnkfumHdRZPw7dJeougI+7KIEXVIo

  - provider: NuGet
    on:
      branch: default
      BMS_RELEASE_INSIGHT_API_TO_NUGET: true
    skip_symbols: false
    artifact: /.*BlackMaple\.FMSInsight\.API.*\.nupkg/
    api_key:
      secure: G2TzGogQH+sScPOuDvM6Cp3lEo8ibadnPBsSnkfumHdRZPw7dJeougI+7KIEXVIo

  - provider: S3
    on:
      branch: default
      BMS_INSTALLER_makino_RELEASE: true
    access_key_id: AKIAIH2IT2INE2ISDGJA
    artifact: /installers.*Makino.*/
    secret_access_key:
      secure: 0r/dAyTIFbRaR3eIfnWdfz1hAYPu85mFntJavbWXsdUYkK6cSa1q6vZXWr2U0mUr
    bucket: com.seedtactics.fms-insight
    region: us-west-2

  - provider: S3
    on:
      branch: default
      BMS_INSTALLER_mazak_RELEASE: true
    access_key_id: AKIAIH2IT2INE2ISDGJA
    artifact: /installers.*Mazak.*/
    secret_access_key:
      secure: 0r/dAyTIFbRaR3eIfnWdfz1hAYPu85mFntJavbWXsdUYkK6cSa1q6vZXWr2U0mUr
    bucket: com.seedtactics.fms-insight
    region: us-west-2

  - provider: S3
    on:
      branch: default
    access_key_id: AKIAIH2IT2INE2ISDGJA
    artifact: website.zip
    unzip: true
    secret_access_key:
      secure: 0r/dAyTIFbRaR3eIfnWdfz1hAYPu85mFntJavbWXsdUYkK6cSa1q6vZXWr2U0mUr
    bucket: com.seedtactics.fms-insight
    region: us-west-2

  - provider: S3
    on:
      branch: default
      BMS_INSTALLER_backup_RELEASE: true
    access_key_id: AKIAIH2IT2INE2ISDGJA
    artifact: /installers.*Backup.*/
    secret_access_key:
      secure: 0r/dAyTIFbRaR3eIfnWdfz1hAYPu85mFntJavbWXsdUYkK6cSa1q6vZXWr2U0mUr
    bucket: com.seedtactics.fms-insight
    region: us-west-2
