version: '{build}'
image: Visual Studio 2017
cache:
  - client/insight/node_modules
install:
- ps: Install-Product node Current
environment:
  bitbucket_auth:
    secure: rWSLJHgb9I+I5jdorS8K2T415gRW5nJ2Z23pM3DmhqQ=

build_script:
- ps: |
    function ver ($x) { c:\python36\python.exe build/version.py $x }
    dotnet build `
        /p:VersionPrefix=$(ver mwi) `
        --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
        server/lib/BlackMaple.MachineWatchInterface
    dotnet build `
        /p:VersionPrefix=$(ver framework) `
        --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
        server/lib/BlackMaple.MachineFramework
    dotnet build `
        /p:VersionPrefix=$(ver mazak) `
        --version-suffix pre.$Env:APPVEYOR_BUILD_NUMBER `
        server/machines/mazak/mazak.csproj

    yarn --cwd client/insight install
    yarn --cwd client/insight run build

after_build:
- ps: |
    $tag = $(hg id -t -r '.^')
    function ver ($x) { c:\python36\python.exe build/version.py $x }
    if ($tag.StartsWith("mwi")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver mwi) `
            server/lib/BlackMaple.MachineWatchInterface
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } elseif ($tag.StartsWith("framework")) {
        dotnet pack `
            --include-symbols `
            -c Release `
            /p:VersionPrefix=$(ver framework) `
            server/lib/BlackMaple.MachineFramework
        Set-AppveyorBuildVariable "BMS_RELEASE_TO_NUGET" "true"
    } elseif ($tag.StartsWith("mazak")) {
        dotnet publish `
            -c Release -f net461 `
            /p:VersionPrefix=$(ver mazak) `
            server/machines/mazak/mazak.csproj

        ./build/insight-installer-build.ps1 mazak $(ver mazak)
        Push-Location
        cd installers
        Remove-Item alias:curl
        curl -X POST `
            --silent --show-error `
            --user $ENV:bitbucket_auth `
            "https://api.bitbucket.org/2.0/repositories/blackmaple/machinewatch/downloads" `
            --form `
            files=@"FMS Insight Mazak Install.msi"
        Pop-Location
    }

- ps: 7z a insight-client.zip .\client\insight\build\*

test_script:
- ps: dotnet test server/test
- ps: ($env:CI = $true) -and (yarn --cwd client/insight test 2>&1 | Write-Host)

artifacts:
  - path: '**/*.nupkg'
    name: NugetPackages

  - path: 'insight-client.zip'
    name: Insight HTML Client

  - path: 'installers/*.msi'
    name: Installers

deploy:
- provider: NuGet
  on:
    branch: default
    BMS_RELEASE_TO_NUGET: true
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: kj0pW91vWRjFl99SLY/sageGAghMFfmqFpNdJd7y+Q73eoImzcsnPCZYlwYxKIhs
