name: build-server

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Server TestSuite
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet test server/test

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn --cwd client/insight install --frozen-lockfile
      - run: yarn --cwd client/insight test
      - run: yarn --cwd client/insight run build

      - name: Install GitVersion
        run: dotnet tool install -g GitVersion.Tool
      - name: Build MachineFramework
        shell: pwsh
        run: |
          $ver = (dotnet gitversion server/lib) | Convert-FromJSON
          dotnet pack `
              --include-symbols `
              -c Release `
              /p:VersionPrefix=$(ver.SemVer) `
              /p:VersionSuffix="" ` # TODO: fix this on branches
              server/lib/BlackMaple.MachineFramework

      - name: Publish Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/SeedTactics/index.json" -UserName SeedTactics -Password $Env.GITHUB_TOKEN
          dotnet nuget push -s GPR server/lib/BlackMaple.MachineFramework
