name: build-server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      # https://github.com/actions/setup-dotnet/issues/29
      #- uses: actions/setup-dotnet@v1.2.0
      #  with:
      #    dotnet-version: "3.0.100"

      #- name: Server TestSuite
      #  run: |
      #    tzutil /s "Pacific Standard Time"
      #    dotnet test server/test

      #- run: yarn --cwd client/insight install --frozen-lockfile
      #- run: yarn --cwd client/insight test
      #- run: yarn --cwd client/insight run build

      - name: Install GitVersion
        run: dotnet tool install -g GitVersion.Tool
      - name: Calculate Version
        shell: pwsh
        run: |
          # GitVersion doesn't like detached heads
          #https://github.com/actions/checkout/issues/6
          git branch --track master remotes/origin/master
          git checkout ($Env:GITHUB_REF.Substring(11))
          $ver = (dotnet gitversion server/lib) | ConvertFrom-Json
          Write-Host ("::set-env name=SEMVER::" + $ver.SemVer)

      - name: print semver
        shell: pwsh
        run: echo $ENV:SEMVER
      - name: Build MachineFramework
        shell: pwsh
        run: dotnet pack -c Release /p:Version="$ENV:SEMVER" server/lib/BlackMaple.MachineFramework
      - name: Build Mazak
        shell: pwsh
        run: dotnet pack -c Release /p:Version="$ENV:SEMVER" server/machines/mazak
      - name: Build Makino
        shell: pwsh
        run: dotnet pack -c Release /p:Version="$ENV:SEMVER" server/machines/makino
      - name: Build Cincron
        shell: pwsh
        run: dotnet pack -c Release /p:Version="$ENV:SEMVER" server/machines/cincron
      # https://github.com/NuGet/Home/issues/8580
      #- name: Setup Nuget
      #  uses: warrenbuckley/Setup-Nuget@v1
      #- name: Add GPR Source
      #  run: nuget sources add -name "GPR" -Source "https://nuget.pkg.github.com/SeedTactics/index.json" -Username SeedTactics -Password ${{ secrets.GITHUB_TOKEN }}
      #- name: Publish MachineFramework
      #  run: nuget push -Source GPR server\lib\BlackMaple.MachineFramework\bin\Release\*.nupkg
      #- name: Publish Mazak
      #  run: nuget push -Source GPR server\machines\mazak\bin\Release\*.nupkg
      #- name: Publish Makino
      #  run: nuget push -Source GPR server\machines\makino\bin\Release\*.nupkg
