name: build-server

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      # https://github.com/actions/setup-dotnet/issues/29
      #- uses: actions/setup-dotnet@v1.2.0
      #  with:
      #    dotnet-version: "3.0.100"

      - name: Server TestSuite
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet test server/test

      - run: yarn --cwd client/insight install --frozen-lockfile
      - run: yarn --cwd client/insight test
      - run: yarn --cwd client/insight run build

      - name: Install GitVersion
        run: dotnet tool install -g GitVersion.Tool
      - name: Build MachineFramework
        shell: pwsh
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          # GitVersion doesn't like detached heads
          #https://github.com/actions/checkout/issues/6
          git checkout ($Env:GITHUB_REF.Substring(11))
          $ver = (dotnet gitversion server/lib) | ConvertFrom-Json
          dotnet pack --include-symbols -c Release /p:Version=$($ver.SemVer) server/lib/BlackMaple.MachineFramework

      - name: Publish Package
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # https://github.com/NuGet/Home/issues/6045
          Set-Content -Path nuget.config -Value @"
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="GPR" value="https://nuget.pkg.github.com/SeedTactics/index.json" />
            </packageSources>
            <packageSourceCredentials>
              <GPR>
                <add key="Username" value="SeedTactics" />
                <add key="ClearTextPassword" value="%GITHUB_TOKEN%" />
              </GPR>
            </packageSourceCredentials>
          </configuration>
          "@
          dotnet nuget push -s GPR server\lib\BlackMaple.MachineFramework\bin\Release\*.nupkg
