name: website

on:
  push:
    branches:
      #- master
      - features/website-builds-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install demo deps
        run: yarn --cwd client/insight install --frozen-lockfile

      - name: Build demo site
        run: yarn --cwd client/insight run build-demo

      - name: Install website deps
        run: yarn --cwd website install

      - name: Build Website
        run: yarn --cwd website run build

      - name: Copy demo to website build output
        shell: pwsh
        run: Copy-Item "client\insight\demo" -Destination "website\build\fms-insight\demo" -Recurse -Force

      - name: Deploy Website
        env:
          GIT_USER: ${{ secrets.WEBSITE_DEPLOY_GITHUB_PAT }}
        run: |
          git config --global user.email "<seedtactics@users.noreply.github.com>"
          git config --global user.name "Github Action"
          yarn --cwd website run publish-gh-pages
