name: website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('client/insight/yarn.lock', 'client/backup-viewer/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install demo deps
        run: yarn --cwd client/insight install --frozen-lockfile

      - name: Build demo site
        run: yarn --cwd client/insight run build-demo

      - name: Copy demo to website build output
        shell: pwsh
        run: Copy-Item "client\insight\demo" -Destination "website\static\demo" -Recurse -Force -Verbose

      - name: Install website deps
        run: yarn --cwd website install

      - name: Deploy Website
        env:
          GIT_USER: ${{ secrets.WEBSITE_DEPLOY_GITHUB_PAT }}
        run: |
          git config --global user.email "<seedtactics@users.noreply.github.com>"
          git config --global user.name "Github Action"
          yarn --cwd website run publish-gh-pages
